import type {
  AssessmentItem,
  StudentSubmission,
} from "../types/assessment.type";

export const MOCK_DATA_ASSESSMENT: AssessmentItem[] = [
  {
    id: 1,
    title: "Python Basics Quiz",
    course: "Introduction to Python",
    submissions: "5/30",
    avgScore: "78%",
    status: "Open",
  },
  {
    id: 2,
    title: "Data Analysis Project",
    course: "Data Science Fundamentals",
    submissions: "N/A",
    avgScore: null,
    status: "Closed",
  },
  {
    id: 3,
    title: "Final Exam",
    course: "Marketing Strategy",
    submissions: "10/20",
    avgScore: "62%",
    status: "Open",
  },
  {
    id: 4,
    title: "Research Paper",
    course: "Modern World History",
    submissions: "18/25",
    avgScore: "70%",
    status: "Open",
  },
  {
    id: 5,
    title: "Network Security Quiz",
    course: "Cybersecurity Essentials",
    submissions: "22/45",
    avgScore: "70%",
    status: "Open",
  },
  {
    id: 6,
    title: "Branding Case Study",
    course: "Creative Design Thinking",
    submissions: "N/A",
    avgScore: null,
    status: "Closed",
  },
  {
    id: 7,
    title: "HTML & CSS Quiz",
    course: "Web Development Fundamentals",
    submissions: "35/40",
    avgScore: "83%",
    status: "Open",
  },
  {
    id: 8,
    title: "User Persona Assignment",
    course: "UX/UI Foundations",
    submissions: "N/A",
    avgScore: null,
    status: "Open",
  },
  {
    id: 9,
    title: "Machine Learning Quiz 1",
    course: "Intro to Machine Learning",
    submissions: "19/30",
    avgScore: "75%",
    status: "Open",
  },
  {
    id: 10,
    title: "Final Project Submission",
    course: "Full-Stack Development Bootcamp",
    submissions: "N/A",
    avgScore: null,
    status: "Closed",
  },
  {
    id: 11,
    title: "React Hooks Deep Dive",
    course: "Advanced React",
    submissions: "12/15",
    avgScore: "88%",
    status: "Open",
  },
  {
    id: 12,
    title: "SQL Database Design",
    course: "Database Mastery",
    submissions: "8/20",
    avgScore: "65%",
    status: "Closed",
  },
];

export const MOCK_SUBMISSIONS: StudentSubmission[] = [
  {
    id: 1,
    studentName: "Saron Mekonnen",
    dateSubmitted: "8 days ago",
    score: 68,
    feedback: null,
  },
  {
    id: 2,
    studentName: "Dawit Tadesse",
    dateSubmitted: "8 days ago",
    score: 72,
    feedback: "Good effort, improve on syntax",
  },
  {
    id: 3,
    studentName: "Helen Yilma",
    dateSubmitted: "8 days ago",
    score: 80,
    feedback: null,
  },
  {
    id: 4,
    studentName: "Abel Getachew",
    dateSubmitted: "2 days ago",
    score: 80,
    feedback: null,
  },
  {
    id: 5,
    studentName: "Bethlehem Gashaw",
    dateSubmitted: "1 days ago",
    score: 90,
    feedback: "Excellent performance!",
  },
];
